# Practica

In [1]:
import numpy as np

##### Numerical Python / Realizar operaciones en paralelo

In [2]:
### Manejo simple de matrices Estructura n dimencional

In [3]:
data = np.random.rand(4,5)

In [4]:
data

array([[0.28562397, 0.16970943, 0.34472412, 0.19610263, 0.10953337],
       [0.65035697, 0.54982128, 0.63713041, 0.9122659 , 0.04253246],
       [0.54188106, 0.61138514, 0.98052506, 0.0407164 , 0.71107825],
       [0.89215894, 0.33021417, 0.41996225, 0.58768158, 0.79242659]])

In [5]:
### Multiplicacion aplicada a todos los elementos
data * 9

array([[2.57061571, 1.52738489, 3.1025171 , 1.76492368, 0.98580034],
       [5.85321272, 4.94839149, 5.73417365, 8.21039308, 0.38279215],
       [4.8769295 , 5.50246623, 8.82472556, 0.36644758, 6.39970424],
       [8.02943045, 2.97192749, 3.77966027, 5.28913421, 7.13183933]])

In [6]:
### Suma de todos los elementos consigo mismo
data + data

array([[0.57124794, 0.33941887, 0.68944825, 0.39220526, 0.21906674],
       [1.30071394, 1.09964255, 1.27426081, 1.8245318 , 0.08506492],
       [1.08376211, 1.22277027, 1.96105012, 0.0814328 , 1.4221565 ],
       [1.78431788, 0.66042833, 0.8399245 , 1.17536316, 1.58485318]])

In [7]:
### Estos arreglos de Numpy se pueden crear con arreglos de Python normales
dataDos = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]

In [8]:
arr = np.array(dataDos)

In [9]:
arr.shape

(4, 3)

In [10]:
arr.ndim

2

##### Creacion de distintos tipos de arreglos

In [11]:
### Arreglos de ceros
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
### Arreglo de 10 elementos, empieza de 0
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
### Arreglo que vaya del 1 al 10 en base a 20 resultados
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

##### Indexando arreglos

In [14]:
arr = np.arange(8)

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
arr[5] ### Posicion 5 contando desde el cero

5

In [18]:
arr[2:5] ### Muesta los elementos del 2 al 5 sin incluir el 5 (El ultimo no se incluye)

array([2, 3, 4])

In [19]:
arr[:] = 1 ### Los dos puntos engloban a todo el arreglo, al igualarlo a 1 estoy cambiando todos los valores a 1

In [20]:
arr

array([1, 1, 1, 1, 1, 1, 1, 1])

##### Slicing

In [21]:
arrDos = [[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]]

In [23]:
arrDosNumpy = np.array(arrDos)

In [24]:
arrDosNumpy.shape

(5, 3)

In [25]:
arrDosNumpy.ndim

2

In [28]:
### Slicing simple
arrDosNumpy[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arrDosNumpy[:2, 1:]

array([[2, 3],
       [5, 6]])

In [36]:
arrDosNumpy[1, :2]

array([4, 5])

In [37]:
arrDosNumpy[1, :2] = 0

In [38]:
arrDosNumpy

array([[ 1,  2,  3],
       [ 0,  0,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

##### start:stop:step

In [39]:
### Se van a tomar los elementos desde start hasta stop saltando de a step elementos
arrStartStopStep = np.arange(10)

In [40]:
arrStartStopStep

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sistaxis <span style="font-weight: bold; color: black">x </span>[<span style="color: green; font-weight: bold;">start</span>:<span style="color: red; font-weight: bold;">stop</span>:<span style="color: blue; font-weight: bold;">step</span>]

In [41]:
arrStartStopStep[2:9:3]

array([2, 5, 8])

##### Índices negativos

In [49]:
arrIndicesNegativos = np.arange(10)

In [50]:
arrIndicesNegativos[-2:10] ## Empeza del total del array menos -2 + 10 = 8 y llega a 10

array([8, 9])

In [51]:
arrIndicesNegativos[-3:3:-1] ### Empeza del total del array menos -3 + 10 = 7 y llega al 3 restando de a un elemento

array([7, 6, 5, 4])